### ISSUE TITLE
Upgrade Reaper to 5.97

### ISSUE THREAD

**Issue by bspeice** [bspeice/au-packages#1]
@wjbuys - I've recreated the repository so I can do things like create issues (not available in forked versions). I've added you back as a collaborator, so this issue is to upgrade Reaper and test that your access works again.

There's potentially an issue because Chocolatey will think 5.965 > 5.97, let me know if you need any assistance working through that.

**Comment by bspeice** [comment]
Given the recent release of 5.971 and the messages on Chocolatey's website asking for an update, I'm going to go ahead and update the package myself.

**Comment by wjbuys** [comment]
Ah, sorry for the lack of response, was out of town and not checking email. I'll get the next one!
