### ISSUE TITLE
libclang-dev and llvm-dev

### ISSUE THREAD

**Issue by aminya** [bspeice/au-packages#13]
Could you add these two to the LLVM package too? or separately?

I need these two packages, and there is no way other than building from source. However, MacOS, Linux, and others have this already.
For example: https://apt.llvm.org/

**Comment by jerome-benoit** [comment]
It's already included in the binaries for Windows shipped by the LLVM project that are installed via chocolatey. If an header is missing in that binaries, just fill a bug report to the LLVM project GitHub.

**Comment by bspeice** [comment]
I'm not sure what you mean by "these two packages". What libraries specifically are you expecting to be there, but aren't? `libclang` is available under the `lib` folder in the LLVM installation for example. 

The chocolatey package simply wraps the binary installation, so if your question was about application development that needs headers to link against LLVM, my recommendation would be to see if there are any other official LLVM docs to guide you.

**Comment by jerome-benoit** [comment]
> The chocolatey package simply wraps the binary installation, so if your question was about application development that needs headers to link against LLVM, my recommendation would be to see if there are any other official LLVM docs to guide you.

GNU/Linux distro packagers split the binaries from the development headers in -dev or -devel packages when building them from source. It's not relevant for chocolatey packages that's just use the installer shipped by the upstream project.

**Comment by bspeice** [comment]
> GNU/Linux distro packagers split the binaries from the development headers in -dev or -devel packages when building them from source.

Yes, I'm aware of the convention. However, the author specifically mentioned building from source, so I was trying to confirm whether they needed the binary libraries (which are included in this package) or the library headers (which are not) and then assist as appropriate.

**Comment by bspeice** [comment]
Closing due to no response.
