### ISSUE TITLE
clang++ depends on vcvarsall.bat being invoked

### ISSUE THREAD

**Issue by jayvdb** [bspeice/au-packages#17]
https://github.com/bspeice/au-packages/issues/13 may have been trying to raise something like this.

When I try to use clang++ after installing llvm on GitHub Actions, I got

```
clang++: warning: unable to find a Visual Studio installation; try running Clang from a developer command prompt [-Wmsvc-not-found]

clang++: warning: argument unused during compilation: '-stdlib=libc++' [-Wunused-command-line-argument]

cases/binit.cpp:1:10: fatal error: 'cassert' file not found
```

The extra bit that I needed was to invoke `vcvarsall.bat`, or using an action:
```yaml
      - name: Set up Visual Studio shell
        uses: egor-tensin/vs-shell@v2
```

It would be great if the LLVM package could emit a warning if `vcvarsall.bat` has (edit: +not) been run.

**Comment by bspeice** [comment]
I'm a bit out of my depth here, but I believe `vcvarsall.bat` is a component of Visual Studio, not LLVM/Clang. For environments that don't use VS (CMake/Ninja for example), this package should still work without issue.

Should the package install really be checking for those environment variables?

**Comment by jayvdb** [comment]
Ya, there are plenty of use cases of LLVM without the C++ headers provided by MSVC.  I am pretty confident clang++ can be used with an alternative set of C++ headers, but that path is for the very brave.  As a result, the warning (or notice?) shouldnt be too stern, or too annoying.  Something like "Note: clang++ does not provide C++ headers on Windows. vcvarsall.bat needs to be run before clang++ can use the MSVC C++ headers".

**Comment by bspeice** [comment]
I'd be fine adding that as a note on installation. Is there an environment variable I can check for to see if `vcvarsall.bat` has already been run and the warning can be skipped?

**Comment by jayvdb** [comment]
https://github.com/eruffaldi/wine_vcpp/blob/master/vcvarsx86_amd64.bat has a 

Probably `VCINSTALLDIR` is the most stable.

Another approach would be to look for a VC program in the PATH.  `cl`?  Other more obscure entries on https://docs.microsoft.com/en-us/cpp/build/reference/c-cpp-build-tools ?

**Comment by bspeice** [comment]
So, I tried it, VCINSTALLDIR does not show up in normal PowerShell sessions, even after install something like Visual Studio Community. [Get-CimInstance](https://docs.microsoft.com/en-us/visualstudio/install/tools-for-managing-visual-studio-instances?view=vs-2019#using-windows-management-instrumentation-wmi) seems to be more reliable, so I'm going to use that.

**Comment by bspeice** [comment]
Alright, should be good to go now. I can't re-release versions of LLVM that already exist, but this will be active starting on the next LLVM update.
