### ISSUE TITLE
Reaper 5.973

### ISSUE THREAD

**Issue by bspeice** [bspeice/au-packages#2]
@wjbuys - you want this one?

**Comment by wjbuys** [comment]
I think I'll only get to this on Friday, a bit swamped at the moment.

**Comment by bspeice** [comment]
No worries, just wanted to confirm you were aware! Let me know if anything comes up.

**Comment by wjbuys** [comment]
This really feels like it would be pretty easy to automate. I think I'll take a look over the weekend. Seems like there's already some Appveyor stuff in this repo that's not used at the moment?

**Comment by bspeice** [comment]
Yeah, I tried to get Appveyor running, but this fell on the [not worth automating](https://xkcd.com/1319/) part of the curve because it was so easy.
