### ISSUE TITLE
Support --side-by-side installation for LLVM

### ISSUE THREAD

**Issue by remss** [bspeice/au-packages#25]
Could you support --side-by-side installation for LLVM? Visual Studio 2019 expects LLVM v12 but Visual Studio 2022 expects LLVM v15 so I need both versions to be installed. Thanks!

**Comment by bspeice** [comment]
I'd be happy to review a pull request that adds the option, but I'm not sure how to pass that through the Chocolatey installer. Do you have any more details on how that could be done?

**Comment by jerome-benoit** [comment]
Something like node, node-lts, node@14, node@16, etc. 

I think the way it's done for such packages can also be used for other packages needing different major versions.

**Comment by bspeice** [comment]
Given this option is already deprecated (https://github.com/chocolatey/choco/issues/2787) and chocolatey plans to remove it (https://docs.chocolatey.org/en-us/create/create-packages#naming-packages-to-allow-for-side-by-side-installation), I'm not planning to add support for this.
