### ISSUE TITLE
llvm installer only adds 64 bit Progam Files to Path

### ISSUE THREAD

**Issue by jwidauer** [bspeice/au-packages#33]
Hi there!
Thanks a lot for your efforts maintaining these packages on chocolatey!

I recently had to install the 32-bit version of llvm, which installed into `C:\Program Files (x86)\LLVM`, as expected.
I however noticed that the `C:\Program Files (x86)\LLVM\bin` directory wasn't added to the path.
After a bit of digging, it seems like the chocolatey installer only adds the 64-bit version (so `C:\Program Files\LLVM\bin`) to the path.
I believe [this](https://github.com/bspeice/au-packages/blob/e3807b64198eb70189424f8824d25c6c319a615a/llvm/tools/chocolateyinstall.ps1#L44) is the line.
Would you be able to confirm this and potentially fix it?

**Comment by bspeice** [comment]
Done in https://github.com/bspeice/au-packages/commit/1419611e5edc3d8aafdb751b7b995a611e5ef452. I couldn't find a consistent way to handle the various combinations of [environment variables](https://stackoverflow.com/questions/9594066/how-to-get-program-files-x86-env-variable) between x64 and x32, as well as detecting [`--forcex86`](https://github.com/chocolatey/choco/blob/45e038331537d14b59734d656ebda3d6acaf899c/src/chocolatey.resources/helpers/functions/Get-ChocolateyWebFile.ps1#L45), so I've just added both paths. This will show up in the next LLVM release.
